### ISSUE TITLE
DW Filebrower does not give me permission to upload.

### ISSUE THREAD

**Issue by ssarkarnetip** [turnermm/dwedit#3]
DW Filebrower does not give me permission to upload.

![DW Filebrowser Error](https://user-images.githubusercontent.com/28353306/60216479-2356ea80-9838-11e9-9419-e34cab4f8ae3.JPG)

When I switch to CKG File Browser, I have no issues with uploading files of any sort.

**Comment by turnermm** [comment]
What is your operating system that DW is running on?  The ckgedit filebrowser may be taking a different route to data/media than the dokuwiki filebrowser.  And an .htaccess file may be standing in your way.

**Comment by ssarkarnetip** [comment]
This is running on Centos 7.  Kernel 12.1.

**Comment by ssarkarnetip** [comment]
Running on nginx  :1.12.2-3

**Comment by turnermm** [comment]
I can't be of any help with nginx, sorry.  But does the dw media manager work if you are in the dokuwiki editor?  The problem isn't with the OS.
Also check to see if it's a selinux problem.  Type at the command line:   `getenforce`.  If it says permissive or diabled then it would not be affected by selinux.  See: https://www.rootusers.com/how-to-enable-or-disable-selinux-in-centos-rhel-7/

**Comment by ssarkarnetip** [comment]
SELinux is in permissive mode.  The folder /.  It says you do not have permission to upload to this folder.  
This folder that my media is in the default /var/www/dokuwiki/data/media folder.  This folder is used and owned by nginx which is the owner of the web service and process.  I changed this folder to all public permissions but I still got the upload error.  It is not likely uploading the the media folder. Which folder does DW file browser put media into by default?

**Comment by ssarkarnetip** [comment]
It does not work to upload the image in dokuwiki editor.

**Comment by turnermm** [comment]
> It does not work to upload the image in dokuwiki editor.

Do you mean if you are not using ckgedit at all, if you disable ckgedit and are working directly with  the dokuwiki editor?

**Comment by ssarkarnetip** [comment]
Correct.  I am using dokuwiki editor and the ckgfile browser without any issues.

**Comment by ssarkarnetip** [comment]
What machine are you testing on?  I can spin up a similar instance to see if those same issues occur.

**Comment by turnermm** [comment]
Tested on Centos and Ubuntu, using apache.  Various browsers on Windows.  Ckgedit has a lot of users, so there are probably various systems and combinations of systems, and this issue hasn't come up before.  I suspect the problem could be with the nginx configuration.  You might ask on the forum if anyone is using nginx with ckgedit.

**Comment by ssarkarnetip** [comment]
I want to add a feature request for a future release.  I would like to verify the software has compatability with the newest nginx releases.  Nginx is cloud friendly and having DW filebrowser work with it would be great.  I have a work around using the CKG file browser to do my wiki work.

**Comment by turnermm** [comment]
I'm afraid I can't help; I don't know nginx, nor do I use a cloud-based directory.  Try the forum, and  as a last resort you can possibly get a programmer with wikimatrix: https://www.wikimatrix.org/consultants/

**Comment by ssarkarnetip** [comment]
No, I am fine.  I am just saying for future releases considering checking functionality with nginx,

**Comment by ssarkarnetip** [comment]
Nginx is just another web server similar to Apache.  Think of it as Apache for cloud.  Configs are very similar and you do not need cloud to test it.  It will run fine as standalone.

**Comment by turnermm** [comment]
I may have misunderstood.  I thought you were saying that ckgedit's DW file browser couldn't access a cloud-based directory, and I thought that this may possibly have to do with ckgedut's implementation of the DW file browser and nginx.

**Comment by ssarkarnetip** [comment]
Thank you for your help.  The latest editor update fixed my file attachment issue.  It is now working in NGINIX.

**Comment by ssarkarnetip** [comment]
Nevermind, I spoke to soon.  It cached my old settings.  I tried again, same error.  I believe that Nginix user is not given the proper permission to upload the file to the server.  I would like to add a feature request for nginix support in the future.  I will still close.
