### ISSUE TITLE
Option to show it only for superusers

### ISSUE THREAD

**Issue by jorbig** [turnermm/dwedit#4]
Great plugin, but could you add a configuration setting that shows the icon only for admins? I don't want it to show for everyone...

**Comment by turnermm** [comment]
What version of dokuwiki/ckgedit are you using?  This change makes sense since ckgedit already has an option which enables this feature.  So the change would logically have to be done in sync with ckgedit.

**Comment by turnermm** [comment]
I've tied this into the ckgedit option `dw_edit_display`.  The `admin` option will give only admin users access to the dokuwiki editor.

**Comment by jorbig** [comment]
Perfect! It works great with the latest release of Dokuwiki & CKGedit. Thank you very much!

Btw, I found a tiny little 'bug': the documentation anchor of the plugin links to https://www.dokuwiki.org/plugin:dewdit (the last part says 'dewdit' instead of 'dwedit').

**Comment by turnermm** [comment]
Where does this error appear? on dokuwiki.org or github? Under ckgedit or dwedit? I haven't been able to find it.  I'll need a link to the page.

**Comment by jorbig** [comment]
In the Extension Manager of my Dokuwiki installation, when I click 'Docs'.

Op do 1 okt. 2020 om 00:04 schreef Myron Turner <notifications@github.com>:

**Comment by turnermm** [comment]
Fixed.  Thank you very much.
